# Generated by Django 3.2.5 on 2021-07-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAlbum',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('num_discs', models.IntegerField(null=True)),
                ('release_year', models.IntegerField(null=True)),
                ('performers', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyArtist',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('is_composer', models.BooleanField(null=True)),
                ('spotify_albums', models.ManyToManyField(to='pongo.SpotifyAlbum')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('spotify_albums', models.ManyToManyField(to='pongo.SpotifyAlbum')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('disc_number', models.IntegerField()),
                ('track_number', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('spotify_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pongo.spotifyalbum')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyImage',
            fields=[
                ('spotify_url', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('image_file', models.ImageField(height_field='height', null=True, upload_to='pongo/', width_field='width')),
                ('spotify_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pongo.spotifyalbum')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyGenre',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('spotify_albums', models.ManyToManyField(to='pongo.SpotifyAlbum')),
                ('spotify_artists', models.ManyToManyField(to='pongo.SpotifyArtist')),
            ],
        ),
        migrations.AddField(
            model_name='spotifyartist',
            name='spotify_tracks',
            field=models.ManyToManyField(to='pongo.SpotifyTrack'),
        ),
    ]
